---
kind: Namespace
apiVersion: v1
metadata:
  name: cattle-system
  labels:
    name: cattle-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
    name: cattle-admin
    namespace: cattle-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: cattle-crb
    namespace: cattle-system
subjects:
  - kind: ServiceAccount
    name: cattle-admin
    namespace: cattle-system
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io

---
kind: Deployment
apiVersion: apps/v1
metadata:
    namespace: cattle-system
    name: cattle
spec:
    replicas: 1
    selector:
      matchLabels:
        app: cattle
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: rancher/rancher:v2.4.0
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/rancher
            name: rancher
        volumes:
        - name: rancher
          hostPath:
            path: /home/rancher
---
apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  type: NodePort
  selector:
    app: cattle
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30800
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30801  
